### ISSUE TITLE
can you please provide an example to use it?

### ISSUE THREAD

**Issue by yangric** [dhcdht/UITableView-DXTemplateLayoutCell#1]
can you please provide an example to use it? thanks, I am confusing with the configuration parameter.
what I am trying to do is putting the dx_heightForCell function into heightForRowAtIndexPath func:
func tableView(tableView: UITableView, heightForRowAtIndexPath indexPath: NSIndexPath) -> CGFloat {
    return tableView.dx_heightForCell("identifier", indexPath, ??)
}

I'm newbie, sorry for the easy question.

PS: I tried "nil", but not working, the height is always 0.333

**Comment by dhcdht** [comment]
You should bind your data in that block. Same as what you've done in "tableView:cellForRowAtIndexPath:"
Like:
cell.entity = self.feedEntities[indexPath.row];

This project is just a wrap of UITableView-FDTemplateLayoutCell, test in demo only.
I think you should use https://github.com/forkingdog/UITableView-FDTemplateLayoutCell.

**Comment by yangric** [comment]
thanks for you reply, embarrassing... I don't know Objective-C... an example in Swift will be appreciated...

**Comment by dhcdht** [comment]
Demo is in the demo directory which is write in Swift.
UITableView-DXTemplateLayoutCell/Demo/Demo/ViewController.swift Line 94.
Call configureCell: atIndexPath: in configuration block, it will bind the data with cell, And then you will have a height if your cell's constraints have no problem.

**Comment by yangric** [comment]
Thank you for your patient on this question, excellent tool.
